export type Locale = "de" | "en";

export const site = {
  name: "Karigami",
  author: "Kaan Gevrek",
  email: "contact@karigami.games",
  url: "https://www.karigami.games",
  itch: "https://karigami.itch.io/",
};

export const content = {
  de: {
    home: "/", otherLocale: "/en", otherLanguage: "Read in English",
    aboutNav: "Über mich", contactNav: "Kontakt", menu: "Menü öffnen", closeMenu: "Menü schließen", skip: "Zum Inhalt",
    eyebrow: "Aus neugierigen Ideen werden kleine Welten.",
    headline: ["Kleine Games.", "Große", "Spielfreude."],
    intro: "Entdecke meine bisherigen, aktuellen und kommenden Projekte.",
    explore: "Games entdecken", currentNav: "Aktuelle Projekte", meet: "Mehr über mich",
    catHint: "Neugierig? Versuch zu klicken!", catLabel: "Mit der Origami-Katze das Farbtheme wechseln", catNote: "NEUGIER HAT IHREN EIGENEN KOPF.",
    catFallen: "Neugier ist der Katze Tod.", catRevived: "Nur ein Scherz.", catTailHint: "Versuch’s mal mit dem Schwanz", catTailLabel: "Mit dem Katzenschwanz die Schrift wechseln",
    fontNames: { default: "Ursprüngliche Schrift wiederhergestellt.", pixel: "Pixel-Schrift aktiviert.", serif: "Times New Roman aktiviert." },
    themeNames: { paper: "Weißes Theme aktiviert.", ink: "Schwarzes Theme aktiviert.", red: "Rotes Theme aktiviert." },
    strip: ["AUS NEUGIER GEMACHT", "FÜR SPIELFREUDE GEBAUT", "EIN BISSCHEN EIGENSINN"],
    gamesLabel: "01 / DIE GAMES", gamesTitle: "Kleine Welten.\nEigene Regeln.",
    appStore: "Im App Store", googlePlay: "Bei Google Play", offline: "Auch offline spielbar",
    pocketDescription: "Platziere Truppen, entwickle Strategien und finde Wege, die Pentagon-Armee zu besiegen.",
    hammerDescription: "Ein Hammer mit Raketenantrieb. Manchmal braucht eine Spielidee nicht mehr, um loszufliegen.",
    itchHeading: "Noch neugierig?", itchDescription: "Mehr von Karigami findest du auf itch.io.", itchCta: "Zu meinem itch.io",
    currentLabel: "02 / AKTUELLE PROJEKTE", currentTitle: "Auf meinem\nSchreibtisch.",
    currentIntro: "Hier ist Platz für die Ideen, an denen ich gerade tüftle.",
    currentSoon: "Die nächste kleine Welt nimmt Form an.", currentSoonBody: "Bald gibt es hier Einblicke in meine aktuellen Projekte.",
    aboutLabel: "03 / ABOUT ME", aboutTitle: "Hey, ich bin KG.",
    aboutLead: "Full Stack & Game Developer.",
    aboutBody: "Karigami ist mein Platz für Games, auf die ich gerade Lust habe. Meistens sind es seltsame Ideen, die mir unter der Dusche einfallen. Oder Dinge, von denen ich mir wünsche, dass es sie schon gäbe. Besonders gerne entwerfe ich tiefgehende Gameplay-Systeme und experimentiere mit spaßigen, ungewöhnlichen Mechaniken.",
    aboutEnd: "Von der ersten Idee bis zum letzten Feinschliff: Ich mache Spiele, weil ich Spiele liebe. Schön, dass du hier bist.",
    maker: "DER KOPF HINTER KARIGAMI", note: "Meine Experimente\n& Erfahrungen", noteFooter: "Eine Seite, eine Anekdote",
    noteHint: "Klick für mehr", noteCover: "Das Titelblatt", noteOpen: "Projektgeschichten aufblättern", noteCollection: "Meine Experimente und Erfahrungen",
    notePrevious: "Vorherige Seite", noteNext: "Nächste Seite", noteBack: "Zum Titelblatt", noteStories: "8 kleine Geschichten", notePlay: "Spielen", notePage: "Seite", noteOf: "von",
    contactLabel: "04 / KONTAKT & SUPPORT", contactTitle: "Lass von dir hören.",
    contactBody: "Eine Frage, eine Idee oder etwas, das im Spiel nicht rundläuft? Schreib mir.",
    copy: "E-Mail-Adresse kopieren", copied: "Adresse kopiert!", copyFailed: "Bitte die E-Mail-Adresse direkt kopieren.",
    supportNote: "Bei Support-Anfragen helfen mir der Spielname, dein Gerät, die OS-Version und eine kurze Beschreibung.",
    privacy: "Datenschutz", imprint: "Impressum", privacyPath: "/datenschutz", imprintPath: "/impressum",
    back: "Zurück zur Startseite", legalLabel: "DAS KLEINGEDRUCKTE", contents: "Auf dieser Seite",
  },
  en: {
    home: "/en", otherLocale: "/", otherLanguage: "Auf Deutsch lesen",
    aboutNav: "About me", contactNav: "Contact", menu: "Open menu", closeMenu: "Close menu", skip: "Skip to content",
    eyebrow: "Turning curious ideas into little worlds.",
    headline: ["Little games.", "Big on", "play."],
    intro: "Have a look at my past, current, and future projects.",
    explore: "Explore games", currentNav: "Current projects", meet: "Learn about me",
    catHint: "Curious? Try clicking!", catLabel: "Change the color theme with the origami cat", catNote: "CURIOSITY HAS A MIND OF ITS OWN.",
    catFallen: "Curiosity killed the cat.", catRevived: "Just kidding.", catTailHint: "Maybe try clicking the tail", catTailLabel: "Change the font with the cat’s tail",
    fontNames: { default: "Original fonts restored.", pixel: "Pixel font activated.", serif: "Times New Roman activated." },
    themeNames: { paper: "Light theme activated.", ink: "Dark theme activated.", red: "Red theme activated." },
    strip: ["MADE OUT OF CURIOSITY", "BUILT FOR THE JOY OF PLAY", "A LITTLE DIFFERENT"],
    gamesLabel: "01 / THE GAMES", gamesTitle: "Little worlds.\nTheir own rules.",
    appStore: "View on App Store", googlePlay: "View on Google Play", offline: "Playable offline, too",
    pocketDescription: "Place troops, strategize and find ways to beat the pentagon army.",
    hammerDescription: "A rocket-powered hammer. Sometimes that’s all a game idea needs to take flight.",
    itchHeading: "Still curious?", itchDescription: "Find more from Karigami on itch.io.", itchCta: "Visit my itch.io",
    currentLabel: "02 / CURRENT PROJECTS", currentTitle: "On my\nworkbench.",
    currentIntro: "A little space for the ideas I’m tinkering with right now.",
    currentSoon: "Another little world is taking shape.", currentSoonBody: "A closer look at my current projects is coming soon.",
    aboutLabel: "03 / ABOUT ME", aboutTitle: "Hey, I’m KG.",
    aboutLead: "Full Stack & Game Developer.",
    aboutBody: "Karigami is my space for the games I feel like making. Usually, they start as strange ideas that come to me in the shower. Or things I wish already existed. I particularly enjoy designing deep gameplay systems & experimenting with fun and unique mechanics.",
    aboutEnd: "From the first idea to the finishing touches: I make games because I love games. Glad you’re here.",
    maker: "THE MIND BEHIND KARIGAMI", note: "My experiments\n& experiences", noteFooter: "One Page One Anecdote",
    noteHint: "click for more", noteCover: "The cover", noteOpen: "Open my project stories", noteCollection: "My experiments and experiences",
    notePrevious: "Previous page", noteNext: "Next page", noteBack: "Back to cover", noteStories: "8 little stories", notePlay: "Play", notePage: "Page", noteOf: "of",
    contactLabel: "04 / CONTACT & SUPPORT", contactTitle: "Let’s hear from you.",
    contactBody: "A question, an idea, or something in a game not quite working? Drop me a line.",
    copy: "Copy email address", copied: "Address copied!", copyFailed: "Please copy the email address directly.",
    supportNote: "For support, please include the game, your device, OS version, and a short description of the issue.",
    privacy: "Privacy", imprint: "Imprint", privacyPath: "/en/privacy", imprintPath: "/en/imprint",
    back: "Back to the homepage", legalLabel: "THE SMALL PRINT", contents: "On this page",
  },
} as const;

export function gameData(locale: Locale) {
  const t = content[locale];
  return [
    { id: "pocketwars", number: "01", name: "PocketWars", subtitle: "FRONTLINES", image: "/assets/Pocketwars_widget.png", description: t.pocketDescription, url: "https://apps.apple.com/de/app/pocketwars-frontlines/id6760602813", androidUrl: "https://play.google.com/store/apps/details?id=com.karegami.pocketwars&pcampaignid=web_share" },
    { id: "thrusthammer", number: "02", name: "ThrustHammer", subtitle: "READY FOR LIFTOFF", image: "/assets/ThrustHammer_widget.png", description: t.hammerDescription, url: "https://apps.apple.com/de/app/thrusthammer/id6769060279", androidUrl: "https://play.google.com/store/apps/details?id=com.karigami.thrusthammer&pcampaignid=web_share" },
  ];
}
